name: Release Code Templates

on:
  push:

jobs:
  ZipAndRelease:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v3
    - name: Zip Templates
      run: zip -qq -r distributed-calculator.zip ./templates/distributed-calculator
    - name: Update GitHub Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/templates-')
      env:
          GHR_PATH: ./distributed-calculator.zip
          GHR_DELETE: true
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    
    
