name: Release VSIX

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  ReleaseVSIX:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v3
  
    - name: Package VSIX
      run: |
        npm install
        npm run build
        npm run package
    - name: Upload VSIX To Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vsix.zip
        path: |
          *.vsix
        
